//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkMeetingRoom
{
    using SparkMeetingRoom.Helpers;
    using System;
    using System.Collections.Generic;
    
    public partial class SparkMeetingUser : IUserState
    {
        public SparkMeetingUser(string firstName, string lastName, string email, bool? isActive, string userName, string password, string salt, DateTime? creationDate)
        {
            FirstName = firstName;
            LastName = lastName;
            Email = email;
            IsActive = isActive;
            UserName = userName;
            Password = password;
            Salt = salt;
            CreationDate = creationDate;
        }

        public SparkMeetingUser()
        {}

        public AppUserState GetUserState()
        {
            return new AppUserState()
            {
                Name = this.UserName,
                Email = this.Email,
                UserId = this.Id.ToString()
            };
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
